export { baseEmailTemplate, formatDate, formatTime } from './base'
export { appointmentConfirmationEmail } from './appointment-confirmation'
export { appointmentReminderEmail } from './appointment-reminder'
export { appointmentCancellationEmail } from './appointment-cancellation'
export { newAppointmentAdminEmail } from './new-appointment-admin'

export type { EmailTemplateData } from './base'
export type { AppointmentConfirmationData } from './appointment-confirmation'
export type { AppointmentReminderData } from './appointment-reminder'
export type { AppointmentCancellationData } from './appointment-cancellation'
export type { NewAppointmentAdminData } from './new-appointment-admin'
