export { baseEmailTemplate, formatDate, formatTime } from './base'
export { appointmentConfirmationEmail } from './appointment-confirmation'
export { appointmentRequestedEmail } from './appointment-requested'
export { appointmentReminderEmail } from './appointment-reminder'
export { appointmentCancellationEmail } from './appointment-cancellation'
export { newAppointmentAdminEmail } from './new-appointment-admin'
export { welcomeEmail } from './welcome'
export { appointmentCancelledAdminEmail } from './appointment-cancelled-admin'

export type { EmailTemplateData } from './base'
export type { AppointmentConfirmationData } from './appointment-confirmation'
export type { AppointmentRequestedData } from './appointment-requested'
export type { AppointmentReminderData } from './appointment-reminder'
export type { AppointmentCancellationData } from './appointment-cancellation'
export type { NewAppointmentAdminData } from './new-appointment-admin'
export type { WelcomeData } from './welcome'
export type { AppointmentCancelledAdminData } from './appointment-cancelled-admin'
